apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-api-deployment
  labels:
    app: heart-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heart-api
  template:
    metadata:
      labels:
        app: heart-api
    spec:
      containers:
      - name: heart-api
        image: heart-api:latest   # Local image for Docker Desktop
        imagePullPolicy: Never    # IMPORTANT for local clusters
        ports:
          - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: MLFLOW_MODEL_URI
            value: "file:///app/models/production_model"
