apiVersion: v1
kind: Service
metadata:
  name: heart-api-service
spec:
  type: NodePort
  selector:
    app: heart-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
