apiVersion: v1
kind: Service
metadata:
  name: heart-ui-service
spec:
  type: NodePort
  selector:
    app: heart-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
